services:
  db:
    container_name: db_app
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: fastapi_app
    build: ./
    ports:
       - "1234:8000"
    depends_on:
      - db
    volumes:
      - .:/fastapi_project
    command: bash -c 'alembic upgrade head; uvicorn main:app --reload --host 0.0.0.0 --port 8000'

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  postgres_data: