services:
  db:
    container_name: db_app
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - .postgres:/var/lib/postgres/data

  app:
    container_name: fastapi_app
    build: ./
    ports:
       - "5.53.124.65:8000:8000"
    depends_on:
      - db
    command: bash -c 'alembic upgrade head; uvicorn main:app --host 0.0.0.0 --port 8000'

volumes:
  postgres_data: