services:
  db:
    container_name: db_app
    image: postgres:16
    env_file:
      - .env
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    container_name: fastapi_app
    build: ./
    ports:
      - "1234:8000"
    depends_on:
      - db
    volumes:
      - .:/fastapi_project
    command: bash -c 'alembic upgrade head && uvicorn src.main:app --reload --host 0.0.0.0 --port 8000'

  redis:
    container_name: redis_fastapi
    image: redis
    volumes:
      - ./redis/data:/data
    expose:
      - 6379
    restart: always

volumes:
  postgres_data:
