services:
  db:
    container_name: db_app
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    container_name: fastapi_app
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/fastapi_project
    command: bash -c 'alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000'

  nginx:
    image: nginx:1.23.3
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cert.pem:/etc/cert.pem
      - ./nginx/key.pem:/etc/key.pem
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data:
