services:
  db:
    container_name: db_app
    image: postgres
    env_file:
      - .env
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    container_name: fastapi_app
    build: ./
    ports:
      - "1234:8000"
    depends_on:
      - db
    volumes:
      - .:/fastapi_project
    command: bash -c 'alembic upgrade head && uvicorn src.main:app --reload --host 0.0.0.0 --port 8000'

  nginx:
    image: nginx
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:
